#!/usr/bin/env python3
"""
Skill Generalist — Skill Generator

Reads accumulated learnings, research notes, and experiment log,
then produces a reusable SKILL.md template that the agent fills in
with concrete instructions.

Usage:
  python3 scripts/generate_skill.py --workspace workspace/my-task --skill-name my-skill
"""

import argparse
import json
import os
from datetime import datetime
from pathlib import Path


def read_file(path: str) -> str:
    """Read file if it exists, else return empty string."""
    if os.path.exists(path):
        with open(path) as f:
            return f.read().strip()
    return ""


def generate_skill(workspace: str, skill_name: str) -> str:
    """Generate a skill from accumulated workspace knowledge."""

    learnings = read_file(os.path.join(workspace, "learnings.md"))
    research = read_file(os.path.join(workspace, "research.md"))
    experiment_log = read_file(os.path.join(workspace, "experiment_log.md"))

    # Read progress for stats
    progress_path = os.path.join(workspace, "progress.json")
    stats = ""
    if os.path.exists(progress_path):
        with open(progress_path) as f:
            progress = json.load(f)
        scores = [it["score"] for it in progress.get("iterations", [])]
        if scores:
            stats = (
                f"- Iterations: {len(scores)}\n"
                f"- Score progression: {' → '.join(str(s) for s in scores)}\n"
                f"- Final score: {scores[-1]}/100\n"
                f"- Best score: {max(scores)}/100\n"
            )

    # Build skill template
    skill_content = f"""---
name: {skill_name}
description: >
  [AGENT: Write a clear, specific description of what this skill does
  and when to use it. Be "pushy" — include trigger phrases so agents
  actually activate this skill when relevant.]
---

# {skill_name}

> Auto-generated by Skill Generalist on {datetime.now().strftime('%Y-%m-%d %H:%M')}
> Distilled from {len(learnings.splitlines())} learnings across iterative exploration.

## Overview

[AGENT: Write 2-3 sentences explaining what problem this skill solves
and the approach that was found to work best.]

## Prerequisites

[AGENT: List required tools, libraries, or setup needed.]

## Step-by-Step Instructions

[AGENT: Synthesize the learnings below into clear, numbered steps
that another agent can follow to solve this type of task WITHOUT
going through the exploration process. This is the core value —
turning exploration into a shortcut.]

## Common Pitfalls

[AGENT: Extract from learnings and experiment log — what approaches
DIDN'T work and why. This prevents future agents from wasting time
on dead ends.]

## Validation

[AGENT: Include how to verify the output is correct. Copy or adapt
the evaluation criteria that were used during the exploration.]

---

## Source Data (for reference)

### Research Findings
{research if research else '[No research notes recorded]'}

### Key Learnings
{learnings if learnings else '[No learnings recorded]'}

### Exploration Stats
{stats if stats else '[No stats available]'}
"""

    # Write to generated-skill directory
    skill_dir = os.path.join(workspace, "generated-skill")
    os.makedirs(skill_dir, exist_ok=True)

    skill_path = os.path.join(skill_dir, "SKILL.md")
    with open(skill_path, "w") as f:
        f.write(skill_content)

    return skill_path


def main():
    parser = argparse.ArgumentParser(description="Generate reusable skill from workspace")
    parser.add_argument("--workspace", required=True, help="Path to workspace")
    parser.add_argument("--skill-name", default="generated-skill", help="Name for the generated skill")
    args = parser.parse_args()

    skill_path = generate_skill(args.workspace, args.skill_name)

    print(f"✅ Skill template generated: {skill_path}")
    print()
    print("Next steps for agent:")
    print("1. Read the generated SKILL.md")
    print("2. Fill in all [AGENT: ...] sections with concrete instructions")
    print("3. Review and trim — keep it focused (2-3 modules, <500 lines)")
    print("4. The skill is ready to install for future use")


if __name__ == "__main__":
    main()
